### ISSUE TITLE
Gitlab webhook not working

### ISSUE THREAD

**Issue by SiebeHodzelmans** [benhutchins/docker-taiga#12]
Hello, 

I have used this image to run Taiga and tried integrating with Gitlab running in another container on the same host, following [these instructions](https://taiga.io/support/gitlab-integration/). Unfortunately Taiga throws an 500 error when Gitlab does a POST to it. WHen I inspect the logs with `docker logs` I see this:

```
Request repr():
<WSGIRequest
path:/api/v1/gitlab-hook,
GET:<QueryDict: {'project': ['1'], 'key': ['c105c81f35ea47b7bbe86dce8c180217']}>,
POST:<QueryDict: {}>,
COOKIES:{'csrftoken': 'ib6nXljqgcQvOFUTODWc1MZvdgv5l9VA',
 'sessionid': 'z68706z3wal7az1hk3sg37vd7lpiw24l'},
META:{'CONTENT_LENGTH': '1734',
 'CONTENT_TYPE': 'application/json',
 'DB_1_ENV_GOSU_VERSION': '1.7',
 'DB_1_ENV_LANG': 'en_US.utf8',
 'DB_1_ENV_PGDATA': '/var/lib/postgresql/data',
 'DB_1_ENV_PG_MAJOR': '9.5',
 'DB_1_ENV_PG_VERSION': '9.5.1-1.pgdg80+1',
 'DB_1_ENV_POSTGRES_PASSWORD': '{pass}',
 'DB_1_ENV_POSTGRES_USER': 'taiga',
 'DB_1_NAME': '/mid6_taiga_1/db_1',
 'DB_1_PORT': 'tcp://172.17.0.3:5432',
 'DB_1_PORT_5432_TCP': 'tcp://172.17.0.3:5432',
 'DB_1_PORT_5432_TCP_ADDR': '172.17.0.3',
 'DB_1_PORT_5432_TCP_PORT': '5432',
 'DB_1_PORT_5432_TCP_PROTO': 'tcp',
 'DB_ENV_GOSU_VERSION': '1.7',
 'DB_ENV_LANG': 'en_US.utf8',
 'DB_ENV_PGDATA': '/var/lib/postgresql/data',
 'DB_ENV_PG_MAJOR': '9.5',
 'DB_ENV_PG_VERSION': '9.5.1-1.pgdg80+1',
 'DB_ENV_POSTGRES_PASSWORD': '{pass}',
 'DB_ENV_POSTGRES_USER': 'taiga',
 'DB_NAME': '/mid6_taiga_1/db',
 'DB_PORT': 'tcp://172.17.0.3:5432',
 'DB_PORT_5432_TCP': 'tcp://172.17.0.3:5432',
 'DB_PORT_5432_TCP_ADDR': '172.17.0.3',
 'DB_PORT_5432_TCP_PORT': '5432',
 'DB_PORT_5432_TCP_PROTO': 'tcp',
 'DJANGO_SETTINGS_MODULE': 'settings',
 'EMAIL_HOST': 'smtp.gmail.com',
 'EMAIL_HOST_PASSWORD': 'casusMID6',
 'EMAIL_HOST_USER': 'siebezuyd@gmail.com',
 'EMAIL_PORT': '587',
 'EMAIL_USE_TLS': 'True',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'GPG_KEY': '97FC712E4C024BBEA48A61ED3A5CA953F73C700D',
 'HOME': '/root',
 'HOSTNAME': 'dev.wolk.local',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,nl;q=0.7,chrome://global/locale/intl.properties;q=0.3',
 'HTTP_CONNECTION': 'close',
 'HTTP_COOKIE': 'csrftoken=ib6nXljqgcQvOFUTODWc1MZvdgv5l9VA; '
                'sessionid=z68706z3wal7az1hk3sg37vd7lpiw24l',
 'HTTP_HOST': 'dev.wolk.local',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) '
                    'Gecko/20100101 Firefox/47.0',
 'HTTP_X_FORWARDED_FOR': '172.16.8.11, 172.17.0.6',
 'HTTP_X_FORWARDED_PROTO': 'http',
 'HTTP_X_REAL_IP': '172.17.0.6',
 'HTTP_X_SCHEME': 'http',
 'LANG': 'en_US.UTF-8',
 'LC_TYPE': 'en_US.UTF-8',
 'MID6_DB_1_ENV_GOSU_VERSION': '1.7',
 'MID6_DB_1_ENV_LANG': 'en_US.utf8',
 'MID6_DB_1_ENV_PGDATA': '/var/lib/postgresql/data',
 'MID6_DB_1_ENV_PG_MAJOR': '9.5',
 'MID6_DB_1_ENV_PG_VERSION': '9.5.1-1.pgdg80+1',
 'MID6_DB_1_ENV_POSTGRES_PASSWORD': '{pass}',
 'MID6_DB_1_ENV_POSTGRES_USER': 'taiga',
 'MID6_DB_1_NAME': '/mid6_taiga_1/mid6_db_1',
 'MID6_DB_1_PORT': 'tcp://172.17.0.3:5432',
 'MID6_DB_1_PORT_5432_TCP': 'tcp://172.17.0.3:5432',
 'MID6_DB_1_PORT_5432_TCP_ADDR': '172.17.0.3',
 'MID6_DB_1_PORT_5432_TCP_PORT': '5432',
 'MID6_DB_1_PORT_5432_TCP_PROTO': 'tcp',
 'NGINX_VERSION': '1.9.7-1~jessie',
 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
 'PATH_INFO': '/api/v1/gitlab-hook',
 'PWD': '/usr/src/taiga-back',
 'PYTHON_PIP_VERSION': '8.0.3',
 'PYTHON_VERSION': '3.4.4',
 'QUERY_STRING': 'project=1&key=c105c81f35ea47b7bbe86dce8c180217',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'POST',
 'RUN_MAIN': 'true',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'dev.wolk.local',
 'SERVER_PORT': '8000',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'SHLVL': '0',
 'TAIGA_DB_HOST': 'db',
 'TAIGA_DB_NAME': 'taiga',
 'TAIGA_DB_PASSWORD': '{pass}',
 'TAIGA_DB_USER': 'taiga',
 'TAIGA_HOSTNAME': 'dev.wolk.local',
 'TAIGA_SECRET_KEY': '{key}',
 'TAIGA_SLEEP': '30',
 'TAIGA_SSL': 'False',
 'TZ': 'UTC',
 'VIRTUAL_HOST': 'dev.*,taiga.*',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='ANSI_X3.4-1968'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=7>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>
-------------------------------------------------------------------------------
[17/Mar/2016 09:58:53] "POST /api/v1/gitlab-hook?project=1&key=c105c81f35ea47b7bbe86dce8c180217 HTTP/1.0" 500 37
ERROR:2016-03-17 09:58:54,292: Internal Server Error: /api/v1/gitlab-hook
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/usr/local/lib/python3.4/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/usr/src/taiga-back/taiga/base/response.py", line 98, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "/usr/src/taiga-back/taiga/base/api/renderers.py", line 632, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/usr/src/taiga-back/taiga/base/api/renderers.py", line 582, in get_context
    raw_data_post_form = self.get_raw_data_form(view, "POST", request)
  File "/usr/src/taiga-back/taiga/base/api/renderers.py", line 510, in get_raw_data_form
    if not self.show_form_for_method(view, method, request, obj):
  File "/usr/src/taiga-back/taiga/base/api/renderers.py", line 450, in show_form_for_method
    view.check_permissions(request)
  File "/usr/src/taiga-back/taiga/base/api/viewsets.py", line 133, in check_permissions
    return super().check_permissions(request, action=action, obj=obj)
  File "/usr/src/taiga-back/taiga/base/api/views.py", line 327, in check_permissions
    for permission in self.get_permissions():
  File "/usr/src/taiga-back/taiga/base/utils/iterators.py", line 29, in _decorator
    return list(function(*args, **kwargs))
  File "/usr/src/taiga-back/taiga/base/api/views.py", line 280, in get_permissions
    view=self)
TypeError: object() takes no parameters
```

I asked for help at [the mailing lists](https://groups.google.com/forum/#!msg/taigaio/vS5s6ZXo70g/ULqKuaOOBwAJ) but they said that I should try asking here.

**Comment by Theaxiom** [comment]
@SiebeHodzelmans You shouldn't post your password to the public internet.

**Comment by benhutchins** [comment]
@SiebeHodzelmans If you're still having this problem please reopen a ticket and I'll try to help you, I was long term afk from github and let some of these issues go unhelped for a time. Sorry for the delay.
