### ISSUE TITLE
docker-compose up errors and Initial login cred ?

### ISSUE THREAD

**Issue by jauyzed** [benhutchins/docker-taiga#14]
What are the credentials for initial login after docker-compose?
username/pass... 
## Also i see this error...

```
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/local/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.4/site-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/src/taiga-back/taiga/projects/apps.py", line 22, in <module>
    from . import signals as handlers
  File "/usr/src/taiga-back/taiga/projects/signals.py", line 21, in <module>
    from taiga.projects.services.tags_colors import update_project_tags_colors_handler, remove_unused_tags
  File "/usr/src/taiga-back/taiga/projects/services/__init__.py", line 21, in <module>
    from .bulk_update_order import update_projects_order_in_bulk
  File "/usr/src/taiga-back/taiga/projects/services/bulk_update_order.py", line 21, in <module>
    from taiga.projects import models
  File "/usr/src/taiga-back/taiga/projects/models.py", line 44, in <module>
    from taiga.projects.notifications.services import (
  File "/usr/src/taiga-back/taiga/projects/notifications/services.py", line 36, in <module>
    from taiga.projects.history.services import (make_key_from_model_object,
  File "/usr/src/taiga-back/taiga/projects/history/services.py", line 42, in <module>
    from taiga.mdrender.service import render as mdrender
  File "/usr/src/taiga-back/taiga/mdrender/__init__.py", line 18, in <module>
    from .service import *
  File "/usr/src/taiga-back/taiga/mdrender/service.py", line 20, in <module>
    import bleach
  File "/usr/local/lib/python3.4/site-packages/bleach/__init__.py", line 8, in <module>
    from html5lib.sanitizer import HTMLSanitizer
ImportError: No module named 'html5lib.sanitizer'
ERROR: Service 'taiga' failed to build: The command '/bin/sh -c python manage.py collectstatic --noinput' returned a non-zero code: 1


```

**Comment by benhutchins** [comment]
@jauyzed The default login is `admin` username and password is `123123` (this is in the README and Taiga docs).

Did you provide a custom `local.py`, if so, can you post it here please. It looks like you might have enabled an extension that didn't get the dependencies installed.

**Comment by benhutchins** [comment]
I'm closing this given the age of the ticket.
