### ISSUE TITLE
Docker container not correctly starting up

### ISSUE THREAD

**Issue by sjoerd222888** [benhutchins/docker-taiga#30]
When trying to run a docker container on a synology server it seems to me the installation does not successfully complete. When the browser connects to Taiga you see "Something happened and our Oompa Loompas are working on it."

I start it with `docker-compose up` and no changes to the docker-compose.yml
I need to start it twice, the first time the database is not yet and the taiga container complains about is.

Output of the console:

```
taiga_1     | Running database check
taiga_1     | Connecting to database:
taiga_1     | dbname='taigadb' user='taiga' host='postgres' password='password'
taiga_1     | Database does not appear to be setup.
taiga_1     | Configuring initial database
taiga_1     | Operations to perform:
taiga_1     |   Apply all migrations: admin, attachments, auth, bitbucket, contact, contenttypes, custom_attributes, djmail, easy_thumbnails, epics, external_apps, feedback, github, gitlab, gogs, history, issues, likes, milestones, notifications, projects, references, sessions, taiga_contrib_slack, tasks, timeline, users, userstorage, userstories, votes, webhooks, wiki
taiga_1     | Running migrations:
taiga_1     |   Applying contenttypes.0001_initial... OK
//.... (a huge amount of this lines)
taiga_1     |   Applying wiki.0005_auto_20161201_1628... OK
taiga_1     | Trying import local.py settings...
taiga_1     | Trying import local.py settings...
taiga_1     | Installed 1 object(s) from 1 fixture(s)
taiga_1     | Trying import local.py settings...
taiga_1     | Installed 2 object(s) from 1 fixture(s)
taiga_1     | Trying import local.py settings...
taiga_1     | CommandError: No fixture named 'initial_role' found.
taiga_1     | Trying import local.py settings...
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/pl/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/nb/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/zh-Hans/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/fi/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/de/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/fr/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/nl/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/es/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/zh-Hant/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/ca/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/ru/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/pt_BR/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/it/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/ja/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/sv/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/en/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/ko/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/tr/LC_MESSAGES
taiga_1     | Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f5bcba940d0>
taiga_1     | Traceback (most recent call last):
taiga_1     |   File "/usr/local/lib/python3.5/weakref.py", line 117, in remove
taiga_1     | TypeError: 'NoneType' object is not callable
taiga_1     | Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f5bcba940d0>
taiga_1     | Traceback (most recent call last):
taiga_1     |   File "/usr/local/lib/python3.5/weakref.py", line 117, in remove
taiga_1     | TypeError: 'NoneType' object is not callable
```

What's going wrong here?

**Comment by sjoerd222888** [comment]
This might be related to https://github.com/benhutchins/docker-taiga/issues/24. The last error though does not appear in the other issue report.

What is strange is that on some machines calling `docker-compose up` just works out of the box (e.g. on my laptop) but on others not (unfortunately on my server, would be happy if it was the other way around).

**Comment by stormanger** [comment]
Docker pull benhutchins/taiga.
And docker run it can not  show registered buttons too.
