### ISSUE TITLE
ascii codec can't encode character

### ISSUE THREAD

**Issue by lifenautjoe** [benhutchins/docker-taiga#47]
I'm getting this error when trying to comment on an issue.
```
--------
taiga_1     | ERROR:2018-04-11 12:35:32,519: Internal Server Error: /api/v1/issues/3
taiga_1     | Traceback (most recent call last):
taiga_1     |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
taiga_1     |     response = get_response(request)
taiga_1     |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
taiga_1     |     response = self._get_response(request)
taiga_1     |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
taiga_1     |     response = self.process_exception_by_middleware(e, request)
taiga_1     |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
taiga_1     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
taiga_1     |   File "/usr/src/taiga-back/taiga/base/api/viewsets.py", line 106, in view
taiga_1     |     return self.dispatch(request, *args, **kwargs)
taiga_1     |   File "/usr/local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
taiga_1     |     return view_func(*args, **kwargs)
taiga_1     |   File "/usr/src/taiga-back/taiga/base/api/views.py", line 461, in dispatch
taiga_1     |     response = self.handle_exception(exc)
taiga_1     |   File "/usr/src/taiga-back/taiga/base/api/views.py", line 458, in dispatch
taiga_1     |     response = handler(request, *args, **kwargs)
taiga_1     |   File "/usr/src/taiga-back/taiga/base/api/mixins.py", line 207, in partial_update
taiga_1     |     return self.update(request, *args, **kwargs)
taiga_1     |   File "/usr/src/taiga-back/taiga/projects/issues/api.py", line 141, in update
taiga_1     |     return super().update(request, *args, **kwargs)
taiga_1     |   File "/usr/local/lib/python3.5/contextlib.py", line 30, in inner
taiga_1     |     return func(*args, **kwds)
taiga_1     |   File "/usr/src/taiga-back/taiga/base/decorators.py", line 60, in decorator
taiga_1     |     return func(self, *args, **kwargs)
taiga_1     |   File "/usr/src/taiga-back/taiga/base/api/mixins.py", line 200, in update
taiga_1     |     self.post_save(self.object, created=False)
taiga_1     |   File "/usr/src/taiga-back/taiga/projects/occ/mixins.py", line 85, in post_save
taiga_1     |     super().post_save(obj, created)
taiga_1     |   File "/usr/src/taiga-back/taiga/projects/history/mixins.py", line 80, in post_save
taiga_1     |     super().post_save(obj, created=created)
taiga_1     |   File "/usr/src/taiga-back/taiga/projects/notifications/mixins.py", line 96, in post_save
taiga_1     |     self.send_notifications(obj)
taiga_1     |   File "/usr/src/taiga-back/taiga/projects/notifications/mixins.py", line 93, in send_notifications
taiga_1     |     services.send_notifications(obj, history=history)
taiga_1     |   File "/usr/local/lib/python3.5/contextlib.py", line 30, in inner
taiga_1     |     return func(*args, **kwds)
taiga_1     |   File "/usr/src/taiga-back/taiga/projects/notifications/services.py", line 234, in send_notifications
taiga_1     |     send_sync_notifications(notification.id)
taiga_1     |   File "/usr/local/lib/python3.5/contextlib.py", line 30, in inner
taiga_1     |     return func(*args, **kwds)
taiga_1     |   File "/usr/src/taiga-back/taiga/projects/notifications/services.py", line 294, in send_sync_notifications
taiga_1     |     email.send(user.email, context, headers=headers)
taiga_1     |   File "/usr/local/lib/python3.5/site-packages/djmail/template_mail.py", line 122, in send
taiga_1     |     return email.send()
taiga_1     |   File "/usr/local/lib/python3.5/site-packages/django/core/mail/message.py", line 342, in send
taiga_1     |     return self.get_connection(fail_silently).send_messages([self])
taiga_1     |   File "/usr/local/lib/python3.5/site-packages/django/core/mail/backends/console.py", line 36, in send_messages
taiga_1     |     self.write_message(message)
taiga_1     |   File "/usr/local/lib/python3.5/site-packages/django/core/mail/backends/console.py", line 23, in write_message
taiga_1     |     self.stream.write('%s\n' % msg_data)
taiga_1     | UnicodeEncodeError: 'ascii' codec can't encode character '\xe1' in position 783: ordinal not in range(128)
```

**Comment by cenggel** [comment]
I have get same error. Have you fix this issue?
