### ISSUE TITLE
Can't create items cause rabbit complains

### ISSUE THREAD

**Issue by Milraun** [benhutchins/docker-taiga#7]
Hi,

I've used your install summary to run taiga as described. I can login and create a project. But when I try to create an item nothing happens. 

Taiga shows the following traceback:

```
ERROR:2015-12-18 11:04:24,896: Internal Server Error: /api/v1/userstories
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/src/taiga-back/taiga/base/api/viewsets.py", line 81, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/src/taiga-back/taiga/base/api/views.py", line 420, in dispatch
    response = self.handle_exception(exc)
  File "/usr/src/taiga-back/taiga/base/api/views.py", line 417, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.4/site-packages/django/db/transaction.py", line 271, in __exit__
    connection.set_autocommit(True)
  File "/usr/local/lib/python3.4/site-packages/transaction_hooks/mixin.py", line 58, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/usr/local/lib/python3.4/site-packages/transaction_hooks/mixin.py", line 38, in run_and_clear_commit_hooks
    func()
  File "/usr/src/taiga-back/taiga/events/signal_handlers.py", line 44, in <lambda>
    emit_event = lambda: events.emit_event_for_model(instance, sessionid=sesionid, type=type)
  File "/usr/src/taiga-back/taiga/events/events.py", line 78, in emit_event_for_model
    data=data)
  File "/usr/src/taiga-back/taiga/events/events.py", line 47, in emit_event
    channel=channel)
  File "/usr/src/taiga-back/taiga/events/backends/rabbitmq.py", line 51, in emit_event
    connection = _make_rabbitmq_connection(self.url)
  File "/usr/src/taiga-back/taiga/events/backends/rabbitmq.py", line 43, in _make_rabbitmq_connection
    password=password, virtual_host=vhost[1:])
  File "/usr/local/lib/python3.4/site-packages/amqp/connection.py", line 183, in __init__
    return self._x_open(virtual_host)
  File "/usr/local/lib/python3.4/site-packages/amqp/connection.py", line 627, in _x_open
    (10, 41),    # Connection.open_ok
  File "/usr/local/lib/python3.4/site-packages/amqp/abstract_channel.py", line 67, in wait
    self.channel_id, allowed_methods)
  File "/usr/local/lib/python3.4/site-packages/amqp/connection.py", line 240, in _wait_method
    self.method_reader.read_method()
  File "/usr/local/lib/python3.4/site-packages/amqp/method_framing.py", line 189, in read_method
    raise m
  File "/usr/local/lib/python3.4/site-packages/amqp/method_framing.py", line 107, in _next_method
    frame_type, channel, payload = read_frame()
  File "/usr/local/lib/python3.4/site-packages/amqp/transport.py", line 154, in read_frame
    frame_header = read(7, True)
  File "/usr/local/lib/python3.4/site-packages/amqp/transport.py", line 277, in _read
    s = recv(n - len(rbuf))
ConnectionResetError: [Errno 104] Connection reset by peer
[18/Dec/2015 11:04:24] "POST /api/v1/userstories HTTP/1.0" 500 37
192.168.99.1 - - [18/Dec/2015:11:04:24 +0000] "POST /api/v1/userstories HTTP/1.1" 500 48 "http://192.168.99.100/project/admin-kanban
1/kanban" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36" "-"
```

And rabbitmq shows the following error:

```
=ERROR REPORT==== 18-Dec-2015::11:04:24 ===
closing AMQP connection <0.588.0> (172.17.0.7:53612 -> 172.17.0.4:5672):
{handshake_error,opening,0,
                 {amqp_error,access_refused,
                             "access to vhost '' refused for user 'guest'",
                             'connection.open'}}
```

Any hint what went wrong ?

Thx 

Jürgen

**Comment by superdump** [comment]
I have the same issue. I'll post here if I figure out a solution.

**Comment by benhutchins** [comment]
I haven't done a lot of use with the taiga-events, it's a complicated service to setup for sure. I'll need to find some time to experiment with this, my guess is that taiga-events is outdated.

**Comment by wzrdtales** [comment]
@benhutchins No, you just configured it wrong:

that amqp urls here
https://github.com/benhutchins/docker-taiga/blob/master/docker-settings.py#L35-L40

should be:

    amqp://guest:guest@rabbit:5672//

instead.

**Comment by ravloony** [comment]
Is there a fix for this?
